// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXzJYoBQ5uECyg8cSqwca9w5WC6u2FRHI',
    appId: '1:832193880569:web:9a42b1bbd538d780ca9d28',
    messagingSenderId: '832193880569',
    projectId: 'e-commerce-app-4519a',
    authDomain: 'e-commerce-app-4519a.firebaseapp.com',
    storageBucket: 'e-commerce-app-4519a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACzeEp8OK6EIklPwiHIY7_EdsJED4DJHY',
    appId: '1:832193880569:android:9cade67042b7c4bfca9d28',
    messagingSenderId: '832193880569',
    projectId: 'e-commerce-app-4519a',
    storageBucket: 'e-commerce-app-4519a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7OAr3xZZ0ABPNg4d8kEgSxBdTp_qIX10',
    appId: '1:832193880569:ios:063e4181ce7247adca9d28',
    messagingSenderId: '832193880569',
    projectId: 'e-commerce-app-4519a',
    storageBucket: 'e-commerce-app-4519a.appspot.com',
    iosBundleId: 'com.example.rePr2Harikrushna2121',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7OAr3xZZ0ABPNg4d8kEgSxBdTp_qIX10',
    appId: '1:832193880569:ios:fc4e3efa6de2afaeca9d28',
    messagingSenderId: '832193880569',
    projectId: 'e-commerce-app-4519a',
    storageBucket: 'e-commerce-app-4519a.appspot.com',
    iosBundleId: 'com.example.rePr2Harikrushna2121.RunnerTests',
  );
}
